import 'package:home_pt/globals.dart';
import 'package:shared_preferences/shared_preferences.dart';

class Initialise {
  Initialise() {

    //circuit number is as follows:
    //1: 1/2/5/10/15 reps
    //2: 2/5/10/20/25 reps
    //3: 5/10/20/30/50 reps
    //4: 10/15/30/60/90 seconds

    // Deck of cards Suits:
    // upper body "S"
    // core "D"
    // full body "H"
    // leg "C"

    // exerciseName(STR), exerciseNamePlural(STR), true, deckOfCardsSuit(S, H, D, C),
    // deckOfCards(TF), HIIT(TF), weights(TF), circuit(TF), circuitNumber(1-4), sets(TF),
    // description(STR), core(TF), biceps(TF), triceps(TF), back(TF), shoulders(TF),
    // quads(TF), fullBody(TF), chest(TF), exerciseImageText(STR),
    // numberOfExerciseImages(INT), lowReps(TF), highReps(TF),
    // AMRAP(TF), dropSet(TF), timeUnderTension(TF)

    //Exercises("", "", true, "N/A", true, true, true, true, 3, true, "", false, false, false, false, false, false, false, false, false, "", 1, false, false, false, false, false),


    exerciseList = [
      Exercises("Ab Roll Out", "Ab Roll Outs", true, "N/A", false, false, true, true, 2, true, "Ab roll out requires an ab roller.\n\nStarting position is on your knees with the ab roller in your hands on the ground below your shoulders. Under control, roll the roller out, and try to go low as you can before your stomach touches the ground, and drive yourself back up to start position.", true, false, false, false, false, false, false, false, false, "AbRollOut", 1, false, true, false, false, false),

      Exercises(
          "Barbell Lunge",
          "Barbell Lunges",
          true,
          "N/A",
          true,
          true,
          true,
          true,
          3,
          true,
          "Barbell lunge requires a barbell.\n\nWith the barbell resting across your shoulders behind your head. Under control, lunge one leg forward and lower your body down until just before your back knee touches the ground. Ensure that the knee of the front leg does not go further forward than the toes. Stand back upright, and bring your foot back so they are back together ready for more",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "BarbellLunge",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Bent Over Row Overhand Grip",
          "Bent Over Rows Overhand Grip",
          true,
          "S",
          true,
          true,
          true,
          true,
          3,
          true,
          "Bent over row requires a barbell",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "BentOverRowOverhandGrip",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Bent Over Row Underhand Grip",
          "Bent Over Rows Underhand Grip",
          true,
          "S",
          true,
          true,
          true,
          true,
          3,
          true,
          "Bent over row requires a barbell",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "BentOverRowUnderhandGrip",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Bicycle",
          "Bicycles",
          true,
          "D",
          true,
          true,
          true,
          true,
          3,
          true,
          "Bicycles require no equipment.\n\nLay on your back with your head slightly raised with hands next to each ear\n\nKeeping one leg extended straight, bend the other knee until the opposite elbow touches the knee. Then straighten that leg as you bend the other leg until the opposite elbow meets the bent knee.\n\nThe focus of this exercise is not the leg movement as much as the rotation of your trunk.",
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "Bicycles",
          2,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Burpee",
          "Burpees",
          true,
          "H",
          true,
          true,
          false,
          true,
          2,
          true,
          "Burpees require no equipment.\n\nStart position is standing upright.\n\nSTEP 1\nBring your hands down to the ground in front of your feet and about shoulder width apart\n\nSTEP 2\nKick your feet back far enough that your body is in a straight line from shoulders to feet in the push up up position\n\nSTEP 3\nConduct a push up (this is for those of a higher physical capability, it can be excluded)\n\nSTEP 4\nJump your feet back just behind your hands where they were originally (This can be done one foot at a time instead of a jump as fatigue sets in)\n\nSTEP 6\nStand upright and conduct a vertical jump getting your feet up off the ground and clapping your hands above your head at the peak of the jump and land safely back on your feet.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          "Burpees",
          9,
          false,
          false,
          false,
          false,
          false),
      Exercises(
          "Bus Driver",
          "Bus Drivers",
          true,
          "S",
          true,
          true,
          true,
          true,
          3,
          true,
          "Bus Drivers require a dumbbell or weight plate or similar.\n\nStarting position is standing upright with weight in your hands. Arms remain straight throughout the entire exercise locked out at the elbows. Bring the weight up until it is shoulder height in front of your body. Steer the 'steering wheel' left until your right hand is vertically above your left hand. Now steer the wheel to the right 180 degrees until your left hand is above your right hand. Return the wheel to the original position in front of your body, and slowly lower the weight back down.",
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          "BusDrivers",
          6,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Cable Cross Over",
          "Cable Cross Overs",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Cable cross overs require a cable machine.\n\n ",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "CableCrossOver",
          1,
          true,
          true,
          true,
          true,
          false),
      Exercises(
          "Cable Rope Overhead Tricep Extension",
          "Cable Rope Overhead Tricep Extensions",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Cable Rope Overhead Tricep Extension is done by standing with your back to the cable machine. Grab the cable rope behind your head and drive up working the triceps, hold, and return to the starting position. Repeat.",
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          "CableRopeOverheadTricepExtension",
          1,
          true,
          true,
          true,
          true,
          false),
      Exercises(
          "Cable Rope Rear Delt Row",
          "Cable Rope Rear Delt Rows",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Cable Rope Rear Delt Rows",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "CableRopeRearDeltRow",
          1,
          true,
          true,
          true,
          true,
          false),
      Exercises(
          "Chest Dip",
          "Chest Dips",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Chest Dips require 1 or 2 x chairs.\n\nUsing 2 chairs for beginners, 1 chair for more medium, and a dip bar or equivalent for a harder workout.\n\nPosition your body so that your arms are grabbing the chair just behind your back. To make this a chest dip, lean your body slightly forward to engage the chest as opposed to just triceps. Lower your body under control until about 90 degrees and push through to raise back up again",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "ChestDip",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Close Grip Barbell Bench Press",
          "Close Grip Barbell Bench Press",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Close Grip Barbell Bench Press is conducted on a flat bench. Similar to flat barbell bench press, the only difference being that you hold the bar closer together and drive up closer to your belly button than your chest to engage the triceps.",
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          "CloseGripBarbellBenchPress",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Crunch",
          "Crunches",
          true,
          "D",
          true,
          true,
          true,
          true,
          3,
          true,
          "Crunches require no equipment.\n\nLying on the ground with knees raised at 90 degrees to the ground, hands across your chest (or behind your head if you prefer) crunch your abs until your shoulder blades are off the ground, squeeze, and lower under control back down to the ground",
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "Crunches",
          2,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Dead Lift",
          "Dead Lifts",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Deadlifts require a barbell.\n\nStand at the bar with your shins touching the bar. Keeping your knees behind your toes, lower your body to grab the bar. Almost running the bar up your shins as you stand up straight, raise your body until you are standing upright with weight in your hands. Do the opposite to lower weight back to the ground under control",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "DeadLift",
          2,
          true,
          true,
          false,
          false,
          false),
      Exercises(
          "Decline Barbell Bench Press",
          "Decline Barbell Bench Press",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Decline barbell bench press requires a decline bench and a barbell.\n\nLaying flat on your back on the bench, push the weight up and down.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "DeclineBarbellBenchPress",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Decline Bench Flye",
          "Decline Bench Flyes",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Decline bench flyes requires a decline bench and 2 x dumbbells.\n\nLaying flat on your back on the bench, hold the weights up with straight arms in front of your face. Opening up your chest lower the weights until your elbows are in a line with your shoulders, pause, raise again.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "DeclineBenchFlye",
          1,
          true,
          true,
          true,
          true,
          false),
      Exercises(
          "Decline Dumbbell Bench Press",
          "Decline Dumbbell Bench Press",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Decline dumbbell bench press requires a decline bench and 2 x dumbbells.\n\nLaying flat on your back on the bench, push the weight up and down.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "DeclineDumbbellBenchPress",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Decline Push Up",
          "Decline Push Ups",
          true,
          "H",
          false,
          true,
          true,
          true,
          3,
          true,
          "Decline Pushups require no equipment.\n\nWith your hands higher than your feet, start with hands about shoulder width apart either side of your chest. Maintaining a straight line throughout your whole body, push yourself up, until your arms are at full extension and shoulders to heels is in a straight line. Lower yourself back down under control until your upper arms are parallel to the ground, then go again\n\nAlternative to this is to do pushups on your knees. You still maintain the straight line in your body, but just from your shoulders to your knees for this variety",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "DeclinePushUp",
          1,
          false,
          true,
          true,
          true,
          true),
      Exercises(
          "Decline Situp",
          "Decline Situps",
          true,
          "D",
          true,
          true,
          true,
          true,
          3,
          true,
          "Decline Situps require a decline bench.\n\nStarting position is laying on your back, legs bent at 90 degrees, hands on your thighs. Raise your upper body up until your wrists touch your knees. Then under control, lower your body back to the ground to the start position",
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "DeclineSitups",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Dumbbell Curl",
          "Dumbbell Curls",
          true,
          "S",
          true,
          true,
          true,
          true,
          3,
          true,
          "Dumbbell Curls require 2 x dumbbells.\n\nStanding upright with a dumbbell (or alternative weight) in each hand, lock in your elbows to your side to prevent them from moving and try not to swing to assist the lift. Moving only at the elbows, raise the dumbbells in front of you until above 90 degrees, squeeze at the top, and then lower back down under control and safely",
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "DumbbellCurl",
          2,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Dumbbell One Arm Tricep Extension",
          "Dumbbell One Arm Tricep Extensions",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Dumbbell One Arm Tricep Extensions requires a single dumbbell.\n\nStanding upright, start position is arm straight above your head with weight at the top. Bending at the elbow, lower the weight carefully behind your head, hold, and drive back up to start position.",
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          "DumbbellOneArmTricepExtension",
          1,
          false,
          true,
          true,
          false,
          false),
      Exercises(
          "Dumbbell Shrug",
          "Dumbbell Shrugs",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Dumbbell Shrugs require 2 x dumbbells.\n\nStanding upright with weights in your hands, arms down your side standing normal. Shrug your shoulders trying to touch your ears with you shoulders, pause, lower again.",
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          "DumbbellShrug",
          1,
          true,
          true,
          false,
          false,
          false),
      Exercises(
          "EZ Bar Curl",
          "EZ Bar Curls",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "EZ Bar Curls require an EZ bar.\n\nStanding upright with arms down straight holding EZ bar, lock in your elbows to your side to prevent them from moving and try not to swing to assist the lift. Moving only at the elbows, raise the EZ bar in front of you until above 90 degrees, squeeze at the top, and then lower back down under control and safely",
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "EZBarCurl",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Flat Barbell Bench Press",
          "Flat Barbell Bench Press",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Flat barbell bench press requires a flat bench and a barbell.\n\nLaying flat on your back on the bench, push the weight up and down.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "FlatBarbellBenchPress",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Flat Bench Flye",
          "Flat Bench Flyes",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Flat bench flyes requires a flat bench and 2 x dumbbells.\n\nLaying flat on your back on the bench, hold the weights up with straight arms in front of your face. Opening up your chest lower the weights until your elbows are in a line with your shoulders, pause, raise again.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "FlatBenchFlyes",
          2,
          true,
          true,
          true,
          true,
          false),
      Exercises(
          "Flat Dumbbell Bench Press",
          "Flat Dumbbell Bench Press",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Flat dumbbell bench press requires a flat bench and 2 x dumbbells.\n\nLaying flat on your back on the bench, push the weight up and down.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "FlatDumbbellBenchPress",
          2,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Front Barbell Squat",
          "Front Barbell Squats",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Front Barbell Squats require a barbell held across the front of your neck either with arms crossed across the barbell, or held at the knurling of the barbell.\n\nStarting position is standing upright, feet shoulder width apart.\n\nKeeping your back straight, conduct a squat, ensuring to keep your chest up, back straight, knees behind your toes. Lower yourself until your thighs are parallel to the ground then push back up through your legs until you are back n the starting position",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "FrontBarbellSquat",
          1,
          true,
          true,
          false,
          false,
          false),
      Exercises(
          "Get Up",
          "Get Ups",
          true,
          "H",
          true,
          true,
          false,
          true,
          3,
          true,
          "Get Ups require no equipment.\n\nGet ups start position is lying on the ground with hands out above your head in a straight line.\n\nWithout your hands touching the ground, bring your hands in, and stand up straight. After standing straight, again, without the use of your hands to push off with, lower your body carefully and extends out again back into the start position",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          "GetUps",
          4,
          false,
          false,
          false,
          false,
          false),
      Exercises(
          "Hack Squat",
          "Hack Squats",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Hack squats require a hack squat rack.\n\nWith your back to the rack, conduct a squat under control and raise back up to the start position.",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "HackSquat",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Halo",
          "Halos",
          true,
          "S",
          true,
          true,
          true,
          true,
          3,
          true,
          "Halos require a dumbbell or weight.\n\nUsing the weight, start position is holding the weight close to the front of your face. Choose a direction to move the weight around your head and, keeping weight close to your head, conduct an entire revolution around your head",
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          "Halos",
          4,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Hammer Curl",
          "Hammer Curls",
          true,
          "S",
          true,
          true,
          true,
          true,
          3,
          true,
          "Hammer curls require 2 x dumbbells\n\nStanding upright with a dumbbell in each hand, keeping your hands facing each other, conduct a curl, moving at the elbow",
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "HammerCurls",
          1,
          false,
          true,
          true,
          true,
          false),
      Exercises(
          "Heave",
          "Heaves",
          true,
          "S",
          false,
          false,
          true,
          true,
          1,
          true,
          "Heaves require a heave beam.\n\nUsing a heave beam or any horizontal bar taller than you, using an overhand grasp (palms facing away from you) start position is hanging freely from the bar. Under control, raise your body until your chin reaches the bar, pause, and lower back down under control back to starting position with arms fully outstretched",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "Heave",
          2,
          true,
          true,
          false,
          false,
          false),
      Exercises(
          "Hip Abductor",
          "Hip Abductors",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Hip Abductors requires the abductor machine.\n\nSitting with your legs on the inside of the foam. Push out against the foam and spread your legs, activating your abductors. Hold, and slowly return to start position.",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "HipAbductors",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Hip Adductor",
          "Hip Adductors",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Hip Adductors requires the adductor machine.\n\nSitting with your legs open and on the outside of the foam. Push in against the foam and close your legs, activating your adductors. Hold, and slowly return to start position.",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "HipAdductors",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Hyperextension",
          "Hyperextensions",
          true,
          "S",
          false,
          false,
          true,
          false,
          1,
          false,
          "Hyperextensions",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "Hyperextension",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Incline Barbell Bench Press",
          "Incline Barbell Bench Press",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Incline barbell bench press requires an incline bench and a barbell.\n\nLaying flat on your back on the bench, push the weight up and down.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "InclineBarbellBenchPress",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Incline Bench Flye",
          "Incline Bench Flyes",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Incline bench flyes requires an incline bench and 2 x dumbbells.\n\nLaying flat on your back on the bench, hold the weights up with straight arms in front of your face. Opening up your chest lower the weights until your elbows are in a line with your shoulders, pause, raise again.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "InclineBenchFlye",
          1,
          true,
          true,
          true,
          true,
          false),
      Exercises(
          "Incline Dumbbell Bench Press",
          "Incline Dumbbell Bench Press",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Incline dumbbell bench press requires an incline bench and a dumbbells.\n\nLaying flat on your back on the bench, push the weight up and down.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "InclineDumbbellBenchPress",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Incline Push Up",
          "Incline Push Ups",
          true,
          "H",
          false,
          true,
          true,
          true,
          3,
          true,
          "Incline Pushups require no equipment.\n\nWith your feet higher than your hands, start with hands about shoulder width apart either side of your chest. Maintaining a straight line throughout your whole body, push yourself off the ground, until your arms are at full extension and shoulders to heels is in a straight line. Lower yourself back down under control until your upper arms are parallel to the ground, then go again\n\nAlternative to this is to do pushups on your knees. You still maintain the straight line in your body, but just from your shoulders to your knees for this variety",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "InclinePushUp",
          2,
          false,
          true,
          true,
          true,
          true),
      Exercises(
          "Lat Pull Down Close Grip",
          "Lat Pull Downs Close Grip",
          true,
          "S",
          false,
          false,
          true,
          false,
          1,
          false,
          "Lat Pull Down Close Grip requires lat pull down machine / cable machine",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "LatPullDownCloseGrip",
          1,
          true,
          true,
          false,
          true,
          false),
      Exercises(
          "Lat Pull Down Wide Grip",
          "Lat Pull Downs Wide Grip",
          true,
          "S",
          false,
          false,
          true,
          false,
          1,
          false,
          "Lat Pull Down Wide Grip requires lat pull down machine / cable machine",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "LatPullDownWideGrip",
          1,
          true,
          true,
          false,
          true,
          false),
      Exercises(
          "Leg Extension",
          "Leg Extensions",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Leg extensions require the leg extension machine.\n\nPlacing your shins against the pad push up and out until your legs are straight, hold, and slowly under control return your legs to the start position.",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "LegExtension",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Leg Press",
          "Leg Press",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Leg press requires the leg press machine.\n\nStart by laying on your back with your feet on the platform. Unhook the weights and drive the weights up until ALMOST straight (do not completely straighten your knees as this could cause serious injury), hold, and slowly return to start position.",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "LegPress",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Lunge",
          "Lunges",
          true,
          "C",
          true,
          true,
          false,
          true,
          3,
          true,
          "Lunges require no equipment.\n\nStart position is standing upright with hands on your hips. Under control, lunge one leg forward and lower your body down until just before your back knee touches the ground. Ensure that the knee of the front leg does not go further forward than the toes. Stand back upright, and bring your foot back so they are back together ready for more",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "Lunge",
          2,
          false,
          false,
          false,
          false,
          false),
      Exercises(
          "Lying Leg Curl",
          "Lying Leg Curls",
          true,
          "N/A",
          false,
          false,
          false,
          false,
          3,
          false,
          "Lying leg curl requires the lying leg curl machine.\n\nLaying on your stomach, position the foam on the back of your calves. Raising until the foam almost touches your bum, hold, and lower under control to the start position.",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "LyingLegCurl",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Lying Tricep Press",
          "Lying Tricep Press",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Lying Tricep Press requires either a barbell, EZ bar or dumbbells.\n\nLaying on a flat bench, raise the weight straight above your face, arms straight. Bending at the elbows, lower the weight above your head, pause, and raise again under control.",
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          "LyingTricepPress",
          1,
          false,
          true,
          true,
          true,
          false),
      Exercises(
          "Mil Press",
          "Mil Press",
          true,
          "S",
          true,
          true,
          false,
          true,
          3,
          true,
          "Mil Press requires a barbell.\n\nMil press is similar to a shoulder press, but instead of pushing the bar straight above your head, you push it up and out at approx 45 degrees.\n\nStart position is standing upright with bar across your chest. Pushing up and out at 45 degrees, press the weight until your arms are fully extended, then under control, bring the weight back to the starting position",
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          "MilPress",
          2,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "One Arm Dumbbell Row",
          "One Arm Dumbbell Rows",
          true,
          "S",
          false,
          false,
          true,
          false,
          1,
          false,
          "One arm dumbbell rows require a dumbbell.\n\nLeaning over, supporting your weight with the opposite arm, raise the weight towards your hip, pause, lower back down.",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "OneArmDumbbellRow",
          1,
          true,
          true,
          false,
          true,
          false),
      Exercises(
          "Overhead Dumbbell Tricep Extension",
          "Overhead Dumbbell Tricep Extensions",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Overhead Dumbbell Tricep Extensions requires 1 x dumbbell.\n\nEither sitting or standing, arms straight up above your head holding the weight. Bending only at the elbows, lower the weight to the back of your head, pause, and push weight back up under control.",
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          "OverheadDumbbellTricepExtensions",
          1,
          false,
          true,
          true,
          true,
          false),
      Exercises(
          "Pistol Squat",
          "Pistol Squats",
          true,
          "C",
          false,
          true,
          true,
          true,
          3,
          true,
          "Pistol Squats require no equipment.\n\nPistol squat is a one-legged squat.\n\nStart position is standing upright on one leg with the other leg out front of your body. Under control, lower your body conducting a squat on the one leg until your thigh is parallel to the ground, trying to keep the leg out front as straight as you can. Push back up off that leg and back up to the starting position.\n\nEnsure your heel remains on the ground the entire time and don't go up onto your toes",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "PistolSquat",
          2,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Plank",
          "Plank",
          true,
          "N/A",
          false,
          false,
          false,
          true,
          4,
          true,
          "Plank requires no equipment.\n\nPlank involves laying on the ground with only your forearms and toes touching the ground. The rest of your body is in a straight line making a 'plank'. Hold this for the duration of the exercise\n\nConcentrate on keeping the straight line and not lifting or lowering your bum",
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "Plank",
          1,
          false,
          false,
          false,
          false,
          false),
      Exercises(
          "Preacher Curl",
          "Preacher Curls",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Preacher Curls require a preacher curl bench and a barbell.\n\nStart with your triceps on the foam and arms out straight holding the barbell. Bending at the elbow, use your biceps to raise the weights until a the top, pause, and lower under control",
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "PreacherCurl",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Pull Up",
          "Pull Ups",
          true,
          "N/A",
          false,
          false,
          true,
          true,
          1,
          true,
          "Pull ups require a heave beam.\n\nPull ups are heaves with your palms facing you.\n\nGrab the heave beam with your palms facing yourself and hang with arms outstretched. Pull yourself up until your chin reaches the bar, squeeze, and lower back down under control until your arms are at full extension again",
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "PullUp",
          2,
          true,
          false,
          false,
          false,
          false),
      Exercises(
          "Push Up",
          "Push Ups",
          true,
          "H",
          false,
          true,
          true,
          true,
          3,
          true,
          "Pushups require no equipment.\n\nLay on the ground on your stomach with hands about shoulder width apart either side of your chest. Maintaining a straight line throughout your whole body, push yourself off the ground, until your arms are at full extension and shoulders to heels is in a straight line. Lower yourself back down under control until your upper arms are parallel to the ground, then go again\n\nAlternative to this is to do pushups on your knees. You still maintain the straight line in your body, but just from your shoulders to your knees for this variety",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          "PushUp",
          2,
          false,
          true,
          true,
          true,
          true),

      Exercises(
          "Reverse Barbell Curl",
          "Reverse Barbell Curls",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          1,
          false,
          "Reverse Barbell Curls require a barbell.\n\nStanding with the weight in front of you arms extended, grasp the bar with your hands facing the ground. Conduct your curls as you do with normal curls, but just the alternate grip on the bar.",
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "ReverseBarbellCurls",
          1,
          true,
          true,
          true,
          true,
          false),
      Exercises(
          "Romanian Dead Lift",
          "Romanian Dead Lifts",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Romanian Deadlifts require a barbell.\n\nStand at the bar with your shins touching the bar. Keeping your knees behind your toes, lower your body to grab the bar. Almost running the bar up your shins as you stand up straight, raise your body until you are standing upright with weight in your hands. Do the opposite to lower weight back to the ground under control",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "RomanianDeadLift",
          1,
          true,
          true,
          false,
          false,
          false),
      Exercises(
          "Rope Straight Arm Pull Down",
          "Rope Straight Arm Pull Downs",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Rope Straight Arm Pull Downs require a cable machine",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "RopeStraightArmPullDown",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Russian Twist",
          "Russian Twists",
          true,
          "D",
          true,
          true,
          true,
          true,
          3,
          true,
          "Russian Twists require a dumbbell or no weight as an alternative.\n\nSitting upright with your feet up off the ground in front of your body, touch the ground on one side of your body with the weight. Rotate through until your body is now facing the opposite direction and tap the weight on the ground. Concentrate on keeping the weight in front of your body and rotating at your hips as opposed to just moving your arms and tapping the weights either side",
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "RussianTwists",
          2,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Seated Cable Row Close Grip",
          "Seated Cable Rows Close Grip",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Seated Cable Row Close Grip",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "SeatedCableRowCloseGrip",
          1,
          true,
          true,
          false,
          true,
          false),
      Exercises(
          "Seated Cable Row Wide Grip",
          "Seated Cable Rows Wide Grip",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Seated Cable Row Wide Grip",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "SeatedCableRowWideGrip",
          1,
          true,
          true,
          false,
          false,
          false),
      Exercises(
          "Seated Calf Raise",
          "Seated Calf Raises",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Seated calf raise requires the seated calf raise machine.\n\nSitting with your quads touching the foam pads with your feet flat, drive the weights up by extending your toes and pushing the weight to the ceiling until your totes are at full extension. Hold, and lower under control until your feet are back to the start position or even your heels lower than your toes for a fuller movement.",
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          "SeatedCalfRaise",
          1,
          true,
          true,
          false,
          false,
          false),
      Exercises(
          "Shoulder Front Raise",
          "Shoulder Front Raises",
          true,
          "S",
          true,
          true,
          true,
          true,
          3,
          true,
          "Shoulder Front Raises require weight of some description.\n\nStanding upright, holding weight in both hands, keep your arms straight. Without swaying your body and under control, raise your arms and weight from the shoulder until the weight is in front of your face with arms still straight, then under control, lower the weight back to the start position",
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          "ShoulderFrontRaise",
          2,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Shoulder Press",
          "Shoulder Press",
          true,
          "S",
          true,
          true,
          true,
          true,
          3,
          true,
          "Shoulder Press requires a pair of dumbbells or a barbell.\n\nStanding upright with bar across your chest. Push the weight up, until the bar is directly above your head with arms out straight. Under control, lower the weight back down to your chest",
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          "ShoulderPress",
          2,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Shoulder Side Raise",
          "Shoulder Side Raises",
          true,
          "S",
          true,
          true,
          true,
          true,
          3,
          true,
          "Shoulder Side Raises require a dumbbell.\n\nStanding upright with weights in each hand to your side. At the same time, raise both arms out, keeping elbows straight, out to the side until your arms are parallel to the ground and you have made a 'T' shape. Under control, lower weights back down until your arms are back down at your side",
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          "ShoulderSideRaise",
          2,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Situp",
          "Situps",
          true,
          "D",
          true,
          true,
          true,
          true,
          3,
          true,
          "Situps require no equipment.\n\nStarting position is laying on your back, legs bent at 90 degrees, hands on your thighs. Raise your upper body up until your wrists touch your knees. Then under control, lower your body back to the ground to the start position",
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "SitUp",
          2,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Sprint",
          "Sprints",
          true,
          "N/A",
          false,
          false,
          false,
          false,
          0,
          false,
          "Sprints require no equipment, but an uninterrupted space of up to 25m.\n\nStarting at one end of the track, run AS HARD AS YOU CAN for the length of your track. When you get to the finish line, slow right down and walk back to the start line and repeat",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          "Sprint",
          1,
          false,
          false,
          false,
          false,
          false),
      Exercises(
          "Squat with Press",
          "Squats with Press",
          true,
          "H",
          true,
          true,
          false,
          true,
          3,
          true,
          "Squats with press require a pair of dumbbells.\n\nStart position is standing upright with dumbbells against your shoulders in front of your body.\n\nSTEP 1\nLower your body into a squat. Ensure that your knees stay behind your toes. Go as low as you can aiming for thighs parallel to the ground\n\nSTEP 2\nPushing up through the legs, Straighten your body so that you are back in the starting position. Weights still just in front of your shoulders.\n\nSTEP3\nKeeping your body straight, push the weights up above your head until your arms are at full extension\n\nSTEP 4\nUnder control, lower weights back to the starting position just in front of your shoulders",
          false,
          false,
          false,
          false,
          true,
          true,
          false,
          true,
          false,
          "SquatWithPress",
          4,
          false,
          false,
          false,
          false,
          false),
      Exercises(
          "Standing Calf Raise",
          "Standing Calf Raises",
          true,
          "H",
          true,
          true,
          true,
          true,
          3,
          true,
          "Standing Calf Raise can be done with or without weights.\n\nStanding up straight, either with or without weights, stand as high up on your toes as you can, pause, and lower down as far as you can go either until your feet are flat or until heel goes below your toes for a bigger stretch.",
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          "StandingCalfRaise",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Straight Arm Dumbbell Pull Over",
          "Straight Arm Dumbbell Pull Overs",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Straight Arm Dumbbell Pull Overs requires a flat bench and a dumbbell",
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "StraightArmDumbbellPullOver",
          1,
          false,
          true,
          false,
          false,
          false),
      Exercises(
          "Tricep Dip",
          "Tricep Dips",
          true,
          "S",
          true,
          true,
          true,
          true,
          3,
          true,
          "Tricep Dips require 1 or 2 x chairs.\n\nUsing 2 chairs for beginners, 1 chair for more medium, and a dip bar or equivalent for a harder workout.\n\nPosition your body so that your arms are grabbing the chair just behind your back. Lower your body under control until about 90 degrees and push through to raise back up again",
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          "TricepDip",
          2,
          true,
          true,
          true,
          false,
          false),
      Exercises(
          "Tricep Dumbbell Kick Back",
          "Tricep Dumbbell Kick Backs",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Tricep dumbbell kick backs require 1 x dumbbell.\n\nStanding bent over at the hips, carry the dumbbell with the upper arm parallel to the ground. Push up moving the forearm until it is straight with the upper arm, pause, lower under control.",
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          "TricepDumbbellKickBack",
          1,
          false,
          true,
          true,
          false,
          false),
      Exercises(
          "Tricep Push Down",
          "Tricep Push Downs",
          true,
          "N/A",
          false,
          false,
          true,
          false,
          3,
          false,
          "Tricep pushdowns",
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          "TricepPushdowns",
          1,
          false,
          true,
          true,
          false,
          false),
      Exercises(
          "Undergrasp Cable Pull Down",
          "Undergrasp Cable Pull Downs",
          true,
          "S",
          false,
          false,
          true,
          false,
          3,
          false,
          "Undergrasp Cable Pull Downs requires a cable machine",
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          "UndergraspCablePullDown",
          1,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Walking Lunge",
          "Walking Lunges",
          true,
          "H",
          true,
          true,
          false,
          true,
          3,
          true,
          "Walking Lunges are done exactly the same as a static lunge, but instead of stepping forward and bringing your front leg back, you step forward and bring your rear leg forward to meet the front leg, then extend that leg forward into the lunge position and so on.",
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "WalkingLunge",
          1,
          false,
          false,
          false,
          false,
          false),
      Exercises(
          "Wall Sit",
          "Wall Sit",
          true,
          "H",
          false,
          false,
          false,
          true,
          4,
          true,
          "Wall sit is done by bending your knees 90 degrees and your upper leg parallel to the ground and your back against a wall. Hold this position without holding onto anything for the time given",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "WallSit",
          1,
          false,
          false,
          false,
          false,
          false),
      Exercises(
          "Weighted Squat",
          "Weighted Squats",
          true,
          "C",
          true,
          false,
          true,
          true,
          3,
          true,
          "Weighted Squats require either dumbbells or a barbell.\n\nWeighted squats are conducted like regular squats, except made harder with a weights across your shoulders.",
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          "WeightedSquat",
          2,
          true,
          true,
          true,
          true,
          true),
      Exercises(
          "Window Wiper",
          "Window Wipers",
          true,
          "D",
          true,
          true,
          true,
          true,
          3,
          true,
          "Window Wipers require no equipment.\n\nStart position is laying on your back, arms out for balance and your legs straight out 90 degrees from your hips. Under control, slowly and deliberately move your legs from side to side touching gently on the ground at either side of the movement.\n\nIf your legs can not remain straight during this exercise, that is no problem, just try to keep them as straight as you can and concentrate on not swinging through from side to side, but have deliberate movements.",
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          "WindowWipers",
          4,
          false,
          true,
          false,
          false,
          false),

    ];

    numberOfDeckOfCardsExercises = 0;

    chestExercises.clear();
    backExercises.clear();
    shoulderExercises.clear();
    legsExercises.clear();
    armExercises.clear();
    coreExercises.clear();
    fullBodyExercises.clear();

    //create chest exercise list
    for (int i = 0; i < newNumberOfExercisesToChooseFrom; i++) {
      if (exerciseList[i].chest) {
        chestExercises
            .add(ExerciseAndIndex(exerciseList[i].exerciseNamePlural, i));
      }
    }

    //create back exercise list
    for (int i = 0; i < newNumberOfExercisesToChooseFrom; i++) {
      if (exerciseList[i].back) {
        backExercises
            .add(ExerciseAndIndex(exerciseList[i].exerciseNamePlural, i));
      }
    }

    //create shoulder exercise list
    for (int i = 0; i < newNumberOfExercisesToChooseFrom; i++) {
      if (exerciseList[i].shoulders) {
        shoulderExercises
            .add(ExerciseAndIndex(exerciseList[i].exerciseNamePlural, i));
      }
    }

    //create leg exercise list
    for (int i = 0; i < newNumberOfExercisesToChooseFrom; i++) {
      if (exerciseList[i].quads || exerciseList[i].calves) {
        legsExercises
            .add(ExerciseAndIndex(exerciseList[i].exerciseNamePlural, i));
      }
    }

    //create arm exercise list
    for (int i = 0; i < newNumberOfExercisesToChooseFrom; i++) {
      if (exerciseList[i].biceps || exerciseList[i].triceps) {
        armExercises
            .add(ExerciseAndIndex(exerciseList[i].exerciseNamePlural, i));
      }
    }

    //create core exercise list
    for (int i = 0; i < newNumberOfExercisesToChooseFrom; i++) {
      if (exerciseList[i].core) {
        coreExercises
            .add(ExerciseAndIndex(exerciseList[i].exerciseNamePlural, i));
      }
    }

    //create full body exercise list
    for (int i = 0; i < newNumberOfExercisesToChooseFrom; i++) {
      if (exerciseList[i].fullBody) {
        fullBodyExercises
            .add(ExerciseAndIndex(exerciseList[i].exerciseNamePlural, i));
      }
    }
  }

/*void setPreferences() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    int i = 0;

    do {
      prefs.setString("isSelected" + i.toString(), "1");

      i++;
    } while (i < newNumberOfExercisesToChooseFrom);
  }*/
}
